-- ============================================================
-- Best Cars Ever — informação histórica curta de cada carro (pt/en/es)
-- Preenche cars.blurb. Rode no SQL Editor.
-- ============================================================

update public.cars set blurb = b.blurb from (values
  ('lancia-stratos-hf', '{"pt":"Projetado pela Bertone, foi o primeiro carro concebido do zero para vencer rali — e dominou o Mundial de Rali nos anos 70.","en":"Designed by Bertone, it was the first car purpose-built to win rallies — and dominated the World Rally Championship in the 70s.","es":"Diseñado por Bertone, fue el primer auto concebido para ganar rallies — y dominó el Mundial de Rally en los 70."}'::jsonb),
  ('lamborghini-countach-lp400', '{"pt":"A cunha de Marcello Gandini definiu o visual do superesportivo e suas portas em tesoura viraram assinatura da Lamborghini.","en":"Marcello Gandini''s wedge defined the supercar silhouette, and its scissor doors became a Lamborghini signature.","es":"La cuña de Marcello Gandini definió la silueta del superdeportivo y sus puertas tijera se volvieron sello de Lamborghini."}'::jsonb),
  ('ferrari-512-bb', '{"pt":"Primeira Ferrari de rua com motor 12 cilindros boxer central-traseiro, marcando uma virada técnica na marca.","en":"Ferrari''s first road car with a mid-rear flat-12 boxer engine, a technical turning point for the marque.","es":"El primer Ferrari de calle con motor bóxer de 12 cilindros central-trasero, un giro técnico para la marca."}'::jsonb),
  ('porsche-959', '{"pt":"Vitrine tecnológica da Porsche: tração integral e biturbo nascidos no Grupo B, anos à frente de seu tempo.","en":"Porsche''s tech showcase: Group B-bred AWD and twin-turbo power, years ahead of its time.","es":"El escaparate tecnológico de Porsche: tracción total y biturbo nacidos del Grupo B, años por delante de su época."}'::jsonb),
  ('ferrari-f40', '{"pt":"O último Ferrari aprovado por Enzo Ferrari e o primeiro carro de rua a passar de 320 km/h.","en":"The last Ferrari signed off by Enzo Ferrari himself, and the first road car to top 320 km/h.","es":"El último Ferrari aprobado por el propio Enzo Ferrari y el primer auto de calle en superar los 320 km/h."}'::jsonb),
  ('lamborghini-countach-25th', '{"pt":"A evolução final do Countach, lançada nos 25 anos da Lamborghini com o desenho mais agressivo da linha.","en":"The final evolution of the Countach, launched for Lamborghini''s 25th anniversary with the line''s most aggressive design.","es":"La evolución final del Countach, lanzada en el 25 aniversario de Lamborghini con el diseño más agresivo de la gama."}'::jsonb),
  ('bugatti-eb110', '{"pt":"O carro que ressuscitou a Bugatti nos anos 90, com V12 quad-turbo e chassi de fibra de carbono pioneiro.","en":"The car that revived Bugatti in the 90s, with a quad-turbo V12 and a pioneering carbon-fibre chassis.","es":"El auto que resucitó a Bugatti en los 90, con V12 quad-turbo y un chasis de fibra de carbono pionero."}'::jsonb),
  ('mclaren-f1', '{"pt":"Com posição de dirigir central e cofre do motor forrado a ouro, foi o carro de rua mais rápido do mundo por anos.","en":"With its central driving position and gold-lined engine bay, it was the world''s fastest road car for years.","es":"Con posición de conducción central y vano motor revestido en oro, fue el auto de calle más rápido del mundo durante años."}'::jsonb),
  ('jaguar-xj220', '{"pt":"O superesportivo mais rápido de sua época, a Jaguar provou que velocidade extrema podia vir embrulhada em elegância britânica.","en":"The fastest supercar of its day, the Jaguar proved extreme speed could come wrapped in British elegance.","es":"El superdeportivo más rápido de su época, el Jaguar demostró que la velocidad extrema podía venir envuelta en elegancia británica."}'::jsonb),
  ('ferrari-enzo', '{"pt":"Batizado com o nome do fundador, levou tecnologia de Fórmula 1 às ruas com freios de carbono-cerâmica e câmbio paddle-shift.","en":"Named after the founder, it brought Formula 1 tech to the road with carbon-ceramic brakes and paddle-shift gears.","es":"Bautizado con el nombre del fundador, llevó la tecnología de Fórmula 1 a la calle con frenos carbono-cerámicos y levas al volante."}'::jsonb),
  ('porsche-carrera-gt', '{"pt":"Seu V10 aspirado nasceu de um projeto de Le Mans; o câmbio manual fez dele um dos últimos superesportivos analógicos.","en":"Its naturally aspirated V10 was born from a Le Mans project; the manual gearbox made it one of the last analog supercars.","es":"Su V10 atmosférico nació de un proyecto de Le Mans; la caja manual lo hizo uno de los últimos superdeportivos analógicos."}'::jsonb),
  ('bugatti-veyron', '{"pt":"Com 1001 cv e motor W16 quad-turbo, foi o primeiro carro de rua a quebrar a barreira dos 400 km/h.","en":"With 1001 hp and a quad-turbo W16, it was the first road car to break the 400 km/h barrier.","es":"Con 1001 cv y un W16 quad-turbo, fue el primer auto de calle en romper la barrera de los 400 km/h."}'::jsonb),
  ('ferrari-laferrari', '{"pt":"Primeiro híbrido da Ferrari com sistema HY-KERS da F1, limitado a 499 unidades e o ápice de uma era.","en":"Ferrari''s first hybrid with F1-derived HY-KERS, limited to 499 units and the pinnacle of an era.","es":"El primer híbrido de Ferrari con sistema HY-KERS de F1, limitado a 499 unidades y la cúspide de una era."}'::jsonb),
  ('mclaren-p1', '{"pt":"Parte da ''santíssima trindade'' híbrida, combinava aerodinâmica ativa e DRS de F1 num míssil afinado para pista.","en":"Part of the hybrid ''holy trinity'', it paired active aero and F1-style DRS in a track-honed missile.","es":"Parte de la ''santísima trinidad'' híbrida, combinaba aerodinámica activa y DRS de F1 en un misil afinado para pista."}'::jsonb),
  ('porsche-918-spyder', '{"pt":"O mais utilizável da trindade híbrida, uniu V8 de competição a motores elétricos com tração integral.","en":"The most usable of the hybrid trinity, it married a racing V8 to electric motors with all-wheel drive.","es":"El más usable de la trinidad híbrida, unió un V8 de competición a motores eléctricos con tracción total."}'::jsonb),
  ('bugatti-chiron-ss', '{"pt":"Sucessor do Veyron, seu W16 de 1578 cv levou a velocidade de rua a outro patamar, passando dos 490 km/h.","en":"Successor to the Veyron, its 1578 hp W16 took road-car speed to another level, exceeding 490 km/h.","es":"Sucesor del Veyron, su W16 de 1578 cv llevó la velocidad de calle a otro nivel, superando los 490 km/h."}'::jsonb),
  ('rimac-nevera', '{"pt":"Hiperesportivo 100% elétrico da Croácia, com quatro motores e mais de 1900 cv que reescreveram os recordes de aceleração.","en":"Croatia''s all-electric hypercar, with four motors and over 1900 hp that rewrote acceleration records.","es":"El hiperdeportivo 100% eléctrico de Croacia, con cuatro motores y más de 1900 cv que reescribieron los récords de aceleración."}'::jsonb),
  ('koenigsegg-jesko', '{"pt":"Projetado para ser o Koenigsegg mais rápido de todos, com câmbio LST de nove marchas e mira em mais de 480 km/h.","en":"Engineered to be the fastest Koenigsegg ever, with a nine-speed LST gearbox and a target beyond 480 km/h.","es":"Diseñado para ser el Koenigsegg más rápido de la historia, con caja LST de nueve marchas y mira en más de 480 km/h."}'::jsonb)
) as b(slug, blurb)
where public.cars.slug = b.slug;
